nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000', 'http://127.0.0.1:3000', 'https://daktylo.fr']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'OPTIONS']
        max_age: 3600
    paths:
        '^/': ~
