# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # 1) les routes d'auth publiques
        auth_public:
            pattern: ^/auth/(request-code|verify-code|login-password)$
            stateless: true

        # 2) les routes d'auth qui ont besoin du JWT
        auth_protected:
            pattern: ^/auth
            stateless: true
            provider: app_user_provider
            jwt: ~

        # le reste
        main:
            pattern: ^/
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        - { path: ^/auth/request-code, roles: PUBLIC_ACCESS }
        - { path: ^/auth/verify-code, roles: PUBLIC_ACCESS }
        - { path: ^/auth/login-password, roles: PUBLIC_ACCESS }
        - { path: ^/auth/set-password, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/auth/refresh, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/me, roles: IS_AUTHENTICATED_FULLY }
